<?php

/**
 * Implements hook_css_alter().
 */
function awesome_css_alter(&$css) {
  // Add CDN Google fonts.
  $googlefonts = '//fonts.googleapis.com/css?family=Lato:400';
  $css[$googlefonts] = array(
    'data' => $googlefonts,
    'type' => 'external',
    'every_page' => TRUE,
    'media' => 'all',
    'preprocess' => FALSE,
    'group' => CSS_AGGREGATE_THEME,
    'browsers' => array('IE' => TRUE, '!IE' => TRUE),
    'weight' => 2,
  );
}